### ISSUE TITLE
Refactor injection support

### ISSUE THREAD

**Issue by lahm86** [LostArtefacts/TRX#1967]
Main tasks
- [x] Move handling fully to TRX
- [x] Refactor the file format to support changes more easily
- [x] Use compression
- [x] Improve applicability tests
- [ ] Extend support fully to TR2

**TR2 progress**

_No dependencies_
- [x] Item position/rotation edits
- [x] Object info
- [x] Room property edits e.g. #1939

_Dependencies_
- [x] Anim data
  - [x] Rewrite anim usage throughout to remove globals and create API
  - [x] Read data via libtrx as standard for both games
- [x] Texture pages/packing
  - [x] Requires tex page limit #1796 
- [x] Tex info injection
  - [x] Requires tex info limit #1795 
- [x] Room texture/face/vertex edits
  - [x] Requires `ROOM_MESH` type per #1938
- [x] Object mesh insertion and edits
  - [x] Requires `OBJECT_MESH` type per #1941

_Misc_
- [ ] Automatic 8-bit conversion of textures
